# Generated by Django 4.0.6 on 2022-07-27 20:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_ntfied'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 20, 20, 23, 119098, tzinfo=utc)),
        ),
    ]
