# Generated by Django 4.0.6 on 2022-07-28 03:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='wallet',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 3, 5, 59, 976307, tzinfo=utc)),
        ),
    ]
