# Generated by Django 4.0.6 on 2022-07-28 06:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_price_product_wallet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wallet',
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 6, 20, 44, 512162, tzinfo=utc)),
        ),
    ]
