# Generated by Django 4.0.6 on 2022-07-27 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('imageUrl', models.PositiveIntegerField(default=1)),
                ('username', models.TextField(default='John Doe')),
            ],
        ),
    ]
