# Generated by Django 4.0.6 on 2022-07-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
